-- MySQL Script generated by MySQL Workbench
-- 11/04/16 22:42:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema farmabook
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema farmabook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `farmabook` DEFAULT CHARACTER SET latin1 ;
USE `farmabook` ;

-- -----------------------------------------------------
-- Table `farmabook`.`laboratorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmabook`.`laboratorio` ;

CREATE TABLE IF NOT EXISTS `farmabook`.`laboratorio` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `farmabook`.`principio_ativo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmabook`.`principio_ativo` ;

CREATE TABLE IF NOT EXISTS `farmabook`.`principio_ativo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmabook`.`classe_terapeutica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmabook`.`classe_terapeutica` ;

CREATE TABLE IF NOT EXISTS `farmabook`.`classe_terapeutica` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `farmabook`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmabook`.`endereco` ;

CREATE TABLE IF NOT EXISTS `farmabook`.`endereco` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(255) NULL DEFAULT NULL,
  `logradouro` VARCHAR(255) NULL DEFAULT NULL,
  `numero` INT NULL DEFAULT NULL,
  `complemento` VARCHAR(255) NULL DEFAULT NULL,
  `referencia` VARCHAR(255) NULL DEFAULT NULL,
  `bairro` VARCHAR(255) NULL DEFAULT NULL,
  `cidade` VARCHAR(255) NULL DEFAULT NULL,
  `estado` VARCHAR(255) NULL DEFAULT NULL,
  `pais` VARCHAR(255) NULL DEFAULT NULL,
  `dataCriacao` DATE NULL DEFAULT NULL,
  `dataAtualizacao` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `farmabook`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmabook`.`usuario` ;

CREATE TABLE IF NOT EXISTS `farmabook`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `dataCriacao` DATE NULL DEFAULT NULL,
  `dataAtualizacao` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `farmabook`.`estoque_pessoal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmabook`.`estoque_pessoal` ;

CREATE TABLE IF NOT EXISTS `farmabook`.`estoque_pessoal` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_estoque_pessoal_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_estoque_pessoal_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `farmabook`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `farmabook`.`farmacia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmabook`.`farmacia` ;

CREATE TABLE IF NOT EXISTS `farmabook`.`farmacia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(255) NULL DEFAULT NULL,
  `dataCriacao` DATE NULL DEFAULT NULL,
  `dataAtualizacao` DATE NULL DEFAULT NULL,
  `endereco_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `endereco_id`),
  INDEX `fk_Farmacia_Endereco_idx` (`endereco_id` ASC),
  CONSTRAINT `fk_Farmacia_Endereco`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `farmabook`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `farmabook`.`medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmabook`.`medicamento` ;

CREATE TABLE IF NOT EXISTS `farmabook`.`medicamento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ean` VARCHAR(255) NULL DEFAULT NULL,
  `cnpj` VARCHAR(255) NULL DEFAULT NULL,
  `ggrem` VARCHAR(255) NULL DEFAULT NULL,
  `registro` VARCHAR(255) NULL DEFAULT NULL,
  `nome_comercial` VARCHAR(255) NULL DEFAULT NULL,
  `composicao` VARCHAR(255) NULL DEFAULT NULL,
  `laboratorio_id` INT(11) NOT NULL,
  `classe_terapeutica_id` INT(11) NOT NULL,
  `principio_ativo_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `laboratorio_id`, `classe_terapeutica_id`, `principio_ativo_id`),
  INDEX `fk_medicamento_laboratorio1_idx` (`laboratorio_id` ASC),
  INDEX `fk_medicamento_classe_terapeutica1_idx` (`classe_terapeutica_id` ASC),
  INDEX `fk_medicamento_formula1_idx` (`principio_ativo_id` ASC),
  CONSTRAINT `fk_medicamento_classe_terapeutica1`
    FOREIGN KEY (`classe_terapeutica_id`)
    REFERENCES `farmabook`.`classe_terapeutica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_formula1`
    FOREIGN KEY (`principio_ativo_id`)
    REFERENCES `farmabook`.`principio_ativo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_laboratorio1`
    FOREIGN KEY (`laboratorio_id`)
    REFERENCES `farmabook`.`laboratorio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `farmabook`.`medicamento_precificado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmabook`.`medicamento_precificado` ;

CREATE TABLE IF NOT EXISTS `farmabook`.`medicamento_precificado` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `preco` DOUBLE NOT NULL,
  `dataCriacao` DATE NULL DEFAULT NULL,
  `dataAtualizacao` DATE NULL DEFAULT NULL,
  `medicamento_id` INT(11) NOT NULL,
  `farmacia_id` INT(11) NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `medicamento_id`, `farmacia_id`, `usuario_id`),
  INDEX `fk_medicamento_precificado_farmacia1_idx` (`farmacia_id` ASC),
  INDEX `fk_medicamento_precificado_medicamento1_idx` (`medicamento_id` ASC),
  INDEX `fk_medicamento_precificado_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_medicamento_precificado_farmacia1`
    FOREIGN KEY (`farmacia_id`)
    REFERENCES `farmabook`.`farmacia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_precificado_medicamento1`
    FOREIGN KEY (`medicamento_id`)
    REFERENCES `farmabook`.`medicamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_precificado_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `farmabook`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `farmabook`.`favorito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmabook`.`favorito` ;

CREATE TABLE IF NOT EXISTS `farmabook`.`favorito` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usario_id` INT(11) NOT NULL,
  `medicamento_precificado_id` INT(11) NOT NULL,
  `favorito_id` INT(11) NOT NULL,
  `favorito_usario_id` INT(11) NOT NULL,
  `favorito_medicamento_precificado_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `usario_id`, `medicamento_precificado_id`, `favorito_id`, `favorito_usario_id`, `favorito_medicamento_precificado_id`),
  INDEX `fk_usario_has_medicamento_precificado_medicamento_precifica_idx` (`medicamento_precificado_id` ASC),
  INDEX `fk_usario_has_medicamento_precificado_usario1_idx` (`usario_id` ASC),
  INDEX `fk_favorito_favorito1_idx` (`favorito_id` ASC, `favorito_usario_id` ASC, `favorito_medicamento_precificado_id` ASC),
  CONSTRAINT `fk_usario_has_medicamento_precificado_medicamento_precificado1`
    FOREIGN KEY (`id`)
    REFERENCES `farmabook`.`medicamento_precificado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usario_has_medicamento_precificado_usario1`
    FOREIGN KEY (`usario_id`)
    REFERENCES `farmabook`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorito_favorito1`
    FOREIGN KEY (`favorito_id` , `favorito_usario_id` , `favorito_medicamento_precificado_id`)
    REFERENCES `farmabook`.`favorito` (`id` , `usario_id` , `medicamento_precificado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `farmabook`.`posologia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmabook`.`posologia` ;

CREATE TABLE IF NOT EXISTS `farmabook`.`posologia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dose` VARCHAR(255) NULL DEFAULT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_posologia_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_posologia_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `farmabook`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `farmabook`.`medicamento_pessoal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmabook`.`medicamento_pessoal` ;

CREATE TABLE IF NOT EXISTS `farmabook`.`medicamento_pessoal` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `quantidade` INT(11) NULL DEFAULT NULL,
  `preco` DOUBLE NULL DEFAULT NULL,
  `data_nova_compra` DATE NULL DEFAULT NULL,
  `estoque_pessoal_id` INT(11) NOT NULL,
  `medicamento_precificado_id` INT(11) NOT NULL,
  `posologia_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `estoque_pessoal_id`, `medicamento_precificado_id`, `posologia_id`),
  INDEX `fk_medicamento_pessoal_estoque_pessoal1_idx` (`estoque_pessoal_id` ASC),
  INDEX `fk_medicamento_pessoal_medicamento_precificado1_idx` (`medicamento_precificado_id` ASC),
  INDEX `fk_medicamento_pessoal_posologia1_idx` (`posologia_id` ASC),
  CONSTRAINT `fk_medicamento_pessoal_estoque_pessoal1`
    FOREIGN KEY (`estoque_pessoal_id`)
    REFERENCES `farmabook`.`estoque_pessoal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_pessoal_medicamento_precificado1`
    FOREIGN KEY (`medicamento_precificado_id`)
    REFERENCES `farmabook`.`medicamento_precificado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_pessoal_posologia1`
    FOREIGN KEY (`posologia_id`)
    REFERENCES `farmabook`.`posologia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `farmabook`.`notificacao_nova_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmabook`.`notificacao_nova_compra` ;

CREATE TABLE IF NOT EXISTS `farmabook`.`notificacao_nova_compra` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `mesagem` VARCHAR(255) NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `usuario_id` INT(11) NOT NULL,
  `medicamento_pessoal_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`, `medicamento_pessoal_id`),
  INDEX `fk_notificacao_nova_compra_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_notificacao_nova_compra_medicamento_pessoal1_idx` (`medicamento_pessoal_id` ASC),
  CONSTRAINT `fk_notificacao_nova_compra_medicamento_pessoal1`
    FOREIGN KEY (`medicamento_pessoal_id`)
    REFERENCES `farmabook`.`medicamento_pessoal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notificacao_nova_compra_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `farmabook`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `farmabook`.`notificacao_promocao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmabook`.`notificacao_promocao` ;

CREATE TABLE IF NOT EXISTS `farmabook`.`notificacao_promocao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `mensagem` VARCHAR(45) NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `usuario_id` INT(11) NOT NULL,
  `medicamento_precificado_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`, `medicamento_precificado_id`),
  INDEX `fk_notificacao_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_notificacao_promocao_medicamento_precificado1_idx` (`medicamento_precificado_id` ASC),
  CONSTRAINT `fk_notificacao_promocao_medicamento_precificado1`
    FOREIGN KEY (`id`)
    REFERENCES `farmabook`.`medicamento_precificado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notificacao_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `farmabook`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
