-- MySQL Script generated by MySQL Workbench
-- 09/30/16 01:41:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema farmabook
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema farmabook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `farmabook` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema farmabook
-- -----------------------------------------------------
USE `farmabook` ;

-- -----------------------------------------------------
-- Table `farmabook`.`estoque_pessoal`
-- -----------------------------------------------------
- -----------------------------------------------------
-- Table `estoque_pessoal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque_pessoal` (
  `id` INT NOT NULL,
  `quantidade` INT NULL,
  `dataEntrada` DATE NULL,
  `dataSaida` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `dataCriacao`  datetime ,
  `dataAtualizacao`  datetime,
  `estoque_pessoal_id` INT NOT NULL,
  PRIMARY KEY (`id`, `estoque_pessoal_id`),
  INDEX `fk_usuario_estoque_pessoal1_idx` (`estoque_pessoal_id` ASC),
  CONSTRAINT `fk_usuario_estoque_pessoal1`
    FOREIGN KEY (`estoque_pessoal_id`)
    REFERENCES `estoque_pessoal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(255) NULL,
  `bairro` VARCHAR(255) NULL,
  `cidade` VARCHAR(255) NULL,
  `estado` VARCHAR(255) NULL,
  `cep` VARCHAR(255) NULL,
  `dataCriacao`  datetime ,
  `dataAtualizacao` datetime ,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(255) NULL,
  `dataCriacao`  datetime ,
  `dataAtualizacao` datetime ,
  `endereco_id` INT NOT NULL,
  PRIMARY KEY (`id`, `endereco_id`),
  INDEX `fk_Farmacia_Endereco_idx` (`endereco_id` ASC),
  CONSTRAINT `fk_Farmacia_Endereco`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorio` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classe_terapeutica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classe_terapeutica` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `principio_ativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `principio_ativo` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medicamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ean` VARCHAR(255) NULL,
  `cnpj` VARCHAR(255) NULL,
  `ggrem` VARCHAR(255) NULL,
  `registro` VARCHAR(255) NULL,
  `nome_comercial` VARCHAR(255) NULL,
  `composicao` VARCHAR(255) NULL,
  `laboratorio_id` INT NOT NULL,
  `classe_terapeutica_id` INT NOT NULL,
  `principio_ativo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `laboratorio_id`, `classe_terapeutica_id`, `principio_ativo_id`),
  INDEX `fk_medicamento_laboratorio1_idx` (`laboratorio_id` ASC),
  INDEX `fk_medicamento_classe_terapeutica1_idx` (`classe_terapeutica_id` ASC),
  INDEX `fk_medicamento_formula1_idx` (`principio_ativo_id` ASC),
  CONSTRAINT `fk_medicamento_laboratorio1`
    FOREIGN KEY (`laboratorio_id`)
    REFERENCES `laboratorio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_classe_terapeutica1`
    FOREIGN KEY (`classe_terapeutica_id`)
    REFERENCES `classe_terapeutica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_formula1`
    FOREIGN KEY (`principio_ativo_id`)
    REFERENCES `principio_ativo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medicamento_precificado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medicamento_precificado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preco` DOUBLE NOT NULL,
  `dataCriacao`  datetime ,
  `dataAtualizacao`  datetime ,
  `farmacia_id` INT NOT NULL,
  `medicamento_id` INT NOT NULL,
  PRIMARY KEY (`id`, `farmacia_id`, `medicamento_id`),
  INDEX `fk_medicamento_precificado_farmacia1_idx` (`farmacia_id` ASC),
  INDEX `fk_medicamento_precificado_medicamento1_idx` (`medicamento_id` ASC),
  CONSTRAINT `fk_medicamento_precificado_farmacia1`
    FOREIGN KEY (`farmacia_id`)
    REFERENCES `farmacia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_precificado_medicamento1`
    FOREIGN KEY (`medicamento_id`)
    REFERENCES `medicamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posologia` (
  `id` INT NOT NULL,
  `dose` VARCHAR(255) NULL,
  `descricao` VARCHAR(255) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_posologia_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_posologia_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medicamento_pessoal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medicamento_pessoal` (
  `id` INT NOT NULL,
  `quantidade` INT NULL,
  `preco` DOUBLE NULL,
  `data_nova_compra` DATE NULL,
  `estoque_pessoal_id` INT NOT NULL,
  `medicamento_precificado_id` INT NOT NULL,
  `posologia_id` INT NOT NULL,
  PRIMARY KEY (`id`, `estoque_pessoal_id`, `medicamento_precificado_id`, `posologia_id`),
  INDEX `fk_medicamento_pessoal_estoque_pessoal1_idx` (`estoque_pessoal_id` ASC),
  INDEX `fk_medicamento_pessoal_medicamento_precificado1_idx` (`medicamento_precificado_id` ASC),
  INDEX `fk_medicamento_pessoal_posologia1_idx` (`posologia_id` ASC),
  CONSTRAINT `fk_medicamento_pessoal_estoque_pessoal1`
    FOREIGN KEY (`estoque_pessoal_id`)
    REFERENCES `estoque_pessoal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_pessoal_medicamento_precificado1`
    FOREIGN KEY (`medicamento_precificado_id`)
    REFERENCES `medicamento_precificado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_pessoal_posologia1`
    FOREIGN KEY (`posologia_id`)
    REFERENCES `posologia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `favorito` (
  `id` INT NOT NULL,
  `usario_id` INT NOT NULL,
  `medicamento_precificado_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usario_id`, `medicamento_precificado_id`),
  INDEX `fk_usario_has_medicamento_precificado_medicamento_precifica_idx` (`medicamento_precificado_id` ASC),
  INDEX `fk_usario_has_medicamento_precificado_usario1_idx` (`usario_id` ASC),
  CONSTRAINT `fk_usario_has_medicamento_precificado_usario1`
    FOREIGN KEY (`usario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usario_has_medicamento_precificado_medicamento_precificado1`
    FOREIGN KEY (`medicamento_precificado_id`)
    REFERENCES `medicamento_precificado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notificacao_promocao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notificacao_promocao` (
  `id` INT NOT NULL,
  `mensagem` VARCHAR(45) NULL,
  `data` DATE NULL,
  `usuario_id` INT NOT NULL,
  `medicamento_precificado_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`, `medicamento_precificado_id`),
  INDEX `fk_notificacao_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_notificacao_promocao_medicamento_precificado1_idx` (`medicamento_precificado_id` ASC),
  CONSTRAINT `fk_notificacao_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notificacao_promocao_medicamento_precificado1`
    FOREIGN KEY (`medicamento_precificado_id`)
    REFERENCES `medicamento_precificado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notificacao_nova_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notificacao_nova_compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mesagem` VARCHAR(255) NULL,
  `data` DATE NULL,
  `usuario_id` INT NOT NULL,
  `medicamento_pessoal_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`, `medicamento_pessoal_id`),
  INDEX `fk_notificacao_nova_compra_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_notificacao_nova_compra_medicamento_pessoal1_idx` (`medicamento_pessoal_id` ASC),
  CONSTRAINT `fk_notificacao_nova_compra_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notificacao_nova_compra_medicamento_pessoal1`
    FOREIGN KEY (`medicamento_pessoal_id`)
    REFERENCES `medicamento_pessoal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estoque_pessoal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque_pessoal` (
  `id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
