-- MySQL Script generated by MySQL Workbench
-- 06/15/17 16:37:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pharmabook
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pharmabook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pharmabook` DEFAULT CHARACTER SET latin1 ;
USE `pharmabook` ;

-- -----------------------------------------------------
-- Table `pharmabook`.`classe_terapeutica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmabook`.`classe_terapeutica` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pharmabook`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmabook`.`pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `nome` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmabook`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmabook`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `pais_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `nome` (`nome` ASC),
  INDEX `fk_estado_pais1_idx` (`pais_id` ASC),
  CONSTRAINT `fk_estado_pais1`
    FOREIGN KEY (`pais_id`)
    REFERENCES `pharmabook`.`pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmabook`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmabook`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidade_estado1_idx` (`estado_id` ASC),
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `pharmabook`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmabook`.`bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmabook`.`bairro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `nome` (`nome` ASC),
  INDEX `fk_bairro_cidade1_idx` (`cidade_id` ASC),
  CONSTRAINT `fk_bairro_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `pharmabook`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmabook`.`tipo_logradouro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmabook`.`tipo_logradouro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `nome` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmabook`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmabook`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(255) NULL,
  `logradouro` VARCHAR(255) NULL,
  `bairro_id` INT NOT NULL,
  `tipo_logradouro_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `logradouro` (`logradouro` ASC),
  INDEX `fk_endereco_bairro1_idx` (`bairro_id` ASC),
  INDEX `fk_endereco_tipo_logradouro1_idx` (`tipo_logradouro_id` ASC),
  CONSTRAINT `fk_endereco_bairro1`
    FOREIGN KEY (`bairro_id`)
    REFERENCES `pharmabook`.`bairro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_tipo_logradouro1`
    FOREIGN KEY (`tipo_logradouro_id`)
    REFERENCES `pharmabook`.`tipo_logradouro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmabook`.`enderecos_entidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmabook`.`enderecos_entidades` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `numero` INT(11) NULL DEFAULT NULL,
  `complemento` VARCHAR(255) NULL DEFAULT NULL,
  `referencia` VARCHAR(255) NULL DEFAULT NULL,
  `data_criacao` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6)	ON UPDATE CURRENT_TIMESTAMP,
  `endereco_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_endereco_farmacia_endereco1_idx` (`endereco_id` ASC),
  CONSTRAINT `fk_endereco_farmacia_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `pharmabook`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pharmabook`.`farmacia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmabook`.`farmacia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(255) NULL DEFAULT NULL,
  `data_criacao` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6)	ON UPDATE CURRENT_TIMESTAMP,
  `endereco_farmacia_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_farmacia_endereco_farmacia1_idx` (`endereco_farmacia_id` ASC),
  CONSTRAINT `fk_farmacia_endereco_farmacia1`
    FOREIGN KEY (`endereco_farmacia_id`)
    REFERENCES `pharmabook`.`enderecos_entidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pharmabook`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmabook`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `sobrenome` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `data_criacao` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6)	ON UPDATE CURRENT_TIMESTAMP,
  `enderecos_entidades_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_enderecos_entidades1_idx` (`enderecos_entidades_id` ASC),
  CONSTRAINT `fk_usuario_enderecos_entidades1`
    FOREIGN KEY (`enderecos_entidades_id`)
    REFERENCES `pharmabook`.`enderecos_entidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pharmabook`.`principio_ativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmabook`.`principio_ativo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pharmabook`.`laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmabook`.`laboratorio` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `cnpj` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `nome` (`nome` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pharmabook`.`unidade_fornecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmabook`.`unidade_fornecimento` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmabook`.`medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmabook`.`medicamento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ean` VARCHAR(255) NULL DEFAULT NULL,
  `ggrem` VARCHAR(255) NULL DEFAULT NULL,
  `registro` VARCHAR(255) NULL DEFAULT NULL,
  `nome_comercial` VARCHAR(255) NULL DEFAULT NULL,
  `composicao` VARCHAR(255) NULL DEFAULT NULL,
  `preco_fabrica` FLOAT NULL DEFAULT NULL,
  `preco_maximo_consumidor` FLOAT NULL DEFAULT NULL,
  `restricao_hospitalar` VARCHAR(255) NULL DEFAULT NULL,
  `laboratorio_id` INT(11) NOT NULL,
  `classe_terapeutica_id` INT(11) NOT NULL,
  `principio_ativo_id` INT(11) NOT NULL,
  `unidade_fornecimento_id` INT NOT NULL,
  PRIMARY KEY (`id`, `laboratorio_id`, `classe_terapeutica_id`, `principio_ativo_id`, `unidade_fornecimento_id`),
  INDEX `fk_medicamento_laboratorio1_idx` (`laboratorio_id` ASC),
  INDEX `fk_medicamento_classe_terapeutica1_idx` (`classe_terapeutica_id` ASC),
  INDEX `fk_medicamento_formula1_idx` (`principio_ativo_id` ASC),
  INDEX `fk_medicamento_unidade_fornecimento1_idx` (`unidade_fornecimento_id` ASC),
  CONSTRAINT `fk_medicamento_classe_terapeutica1`
    FOREIGN KEY (`classe_terapeutica_id`)
    REFERENCES `pharmabook`.`classe_terapeutica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_formula1`
    FOREIGN KEY (`principio_ativo_id`)
    REFERENCES `pharmabook`.`principio_ativo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_laboratorio1`
    FOREIGN KEY (`laboratorio_id`)
    REFERENCES `pharmabook`.`laboratorio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_unidade_fornecimento1`
    FOREIGN KEY (`unidade_fornecimento_id`)
    REFERENCES `pharmabook`.`unidade_fornecimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pharmabook`.`medicamento_precificado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmabook`.`medicamento_precificado` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `preco` DOUBLE NOT NULL,
  `historico` TEXT NULL,
  `data_criacao` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `data_atualizacao` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6)	ON UPDATE CURRENT_TIMESTAMP,
  `medicamento_precificado_historia_id` INT NOT NULL,
  `criador_id` INT(11) NOT NULL,
  `atualizador_id` INT(11) NOT NULL,
  `medicamento_id` INT(11) NOT NULL,
  `farmacia_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `criador_id`, `atualizador_id`, `medicamento_id`, `farmacia_id`),
  INDEX `fk_medicamento_precificado_farmacia1_idx` (`farmacia_id` ASC),
  INDEX `fk_medicamento_precificado_medicamento1_idx` (`medicamento_id` ASC),
  INDEX `fk_medicamento_precificado_usuario1_idx` (`criador_id` ASC),
  INDEX `fk_medicamento_precificado_usuario2_idx` (`atualizador_id` ASC),
  CONSTRAINT `fk_medicamento_precificado_farmacia1`
    FOREIGN KEY (`farmacia_id`)
    REFERENCES `pharmabook`.`farmacia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_precificado_medicamento1`
    FOREIGN KEY (`medicamento_id`)
    REFERENCES `pharmabook`.`medicamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_precificado_usuario1`
    FOREIGN KEY (`criador_id`)
    REFERENCES `pharmabook`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_precificado_usuario2`
    FOREIGN KEY (`atualizador_id`)
    REFERENCES `pharmabook`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pharmabook`.`favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmabook`.`favorito` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NOT NULL,
  `medicamento_precificado_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`, `medicamento_precificado_id`),
  INDEX `fk_usario_has_medicamento_precificado_medicamento_precifica_idx` (`id` ASC),
  INDEX `fk_favorito_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_favorito_medicamento_precificado1_idx` (`medicamento_precificado_id` ASC),
  CONSTRAINT `fk_favorito_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `pharmabook`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorito_medicamento_precificado1`
    FOREIGN KEY (`medicamento_precificado_id`)
    REFERENCES `pharmabook`.`medicamento_precificado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pharmabook`.`medicamento_pessoal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmabook`.`medicamento_pessoal` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `validade` DATE NULL,
  `quantidade` INT(11) NULL,
  `capacidade_recipiente` FLOAT NULL,
  `tipo_unidade` VARCHAR(10) NULL,
  `administracao` VARCHAR(20) CHARACTER SET 'utf8' NULL,
  `medicamento_forma` VARCHAR(45) NULL,
  `usuario_id` INT(11) NOT NULL,
  `medicamento_id` INT(11) NOT NULL,
  `data_criacao` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6)	ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `usuario_id`, `medicamento_id`),
  INDEX `fk_medicamento_pessoal_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_medicamento_pessoal_medicamento1_idx` (`medicamento_id` ASC),
  CONSTRAINT `fk_medicamento_pessoal_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `pharmabook`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_pessoal_medicamento1`
    FOREIGN KEY (`medicamento_id`)
    REFERENCES `pharmabook`.`medicamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pharmabook`.`notificacao_medicamento_pessoal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmabook`.`notificacao_medicamento_pessoal` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `mesagem` VARCHAR(255) NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `medicamento_pessoal_id` INT(11) NOT NULL,
  `data_criacao` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6)	ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `medicamento_pessoal_id`),
  INDEX `fk_notificacao_nova_compra_medicamento_pessoal1_idx` (`medicamento_pessoal_id` ASC),
  CONSTRAINT `fk_notificacao_nova_compra_medicamento_pessoal1`
    FOREIGN KEY (`medicamento_pessoal_id`)
    REFERENCES `pharmabook`.`medicamento_pessoal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pharmabook`.`notificacao_promocao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmabook`.`notificacao_promocao` (
  `mensagem` VARCHAR(45) NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `favorito_id` INT(11) NOT NULL,
  `data_criacao` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `data_atualizacao` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6)	ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`favorito_id`),
  INDEX `fk_notificacao_promocao_favorito1_idx` (`favorito_id` ASC),
  CONSTRAINT `fk_notificacao_promocao_favorito1`
    FOREIGN KEY (`favorito_id`)
    REFERENCES `pharmabook`.`favorito` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pharmabook`.`posologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmabook`.`posologia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dose` DOUBLE NULL DEFAULT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `periodicidade` INT NULL,
  `tipo_periodicidade` VARCHAR(255) NULL,
  `data_criacao` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `data_atualizacao` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6)	ON UPDATE CURRENT_TIMESTAMP,
  `medicamento_pessoal_id` INT(11) NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `medicamento_pessoal_id`, `usuario_id`),
  INDEX `fk_posologia_medicamento_pessoal1_idx` (`medicamento_pessoal_id` ASC, `usuario_id` ASC),
  CONSTRAINT `fk_posologia_medicamento_pessoal1`
    FOREIGN KEY (`medicamento_pessoal_id` , `usuario_id`)
    REFERENCES `pharmabook`.`medicamento_pessoal` (`id` , `usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
